export const projects = [
  {
    title: "SupportDesk App",
    description: "App that helps customers to logg thier issues and track them",
    image: "/images/supportdesk.png",
    tags: ["Mongo", "Express", "React", "Node"],
    source: "https://google.com",
    visit: "https://github.com/mento-mume/support-desk-app",
    id: 0,
  },
  {
    title: "Goals App",
    description:
      "This app provides a platform for users to define thier goals, break them down into manageable tasks or milestones and monitor progress over time",
    image: "/images/goals.png",
    tags: ["Mongo", "Express", "React", "Node"],
    source: "https://google.com",
    visit: "https://github.com/mento-mume/mern-refresher",
    id: 1,
  },
  {
    title: "Github Finder",
    description:
      "This platform is for users to search for github user profiles",
    image: "/images/githubfinder.png",
    tags: ["React", "github APIs"],
    source: "https://github-finder-dusky-six.vercel.app/",
    visit: "https://github.com/mento-mume/github-finder",
    id: 2,
  },
  {
    title: "Home Marketplace",
    description:
      "This is platform that provides users the opportunity to put thier landed properties for sell or rent",
    image: "/images/home.png",
    tags: ["React", "Firebase"],
    source: "https://home-marketplace-omega.vercel.app/",
    visit: "https://github.com/mento-mume/home-marketplace",
    id: 3,
  },
  {
    title: "Restaurant",
    description: "Lovely landing page for a restaurant. it is mobile friendly",
    image: "/images/restaurant.png",
    tags: ["React"],
    source: "https://restaurant-site-alpha-one.vercel.app/",
    visit: "https://github.com/mento-mume/restaurant-site",
    id: 4,
  },
  {
    title: "Chatgpt Website",
    description:
      "Proper landing page for a web3 website. Mobile friendly as well",
    image: "/images/chatgpt.png",
    tags: ["React"],
    source: "https://chatgpt-tau-henna.vercel.app/",
    visit: "https://github.com/mento-mume/chatgpt",
    id: 5,
  },
  {
    title: "Imager",
    description: "App that allows users store up thier memories",
    image: "/images/img.png",
    tags: ["React"],
    source: "https://imgstore.vercel.app/",
    visit: "https://github.com/mento-mume?tab=repositories",
    id: 6,
  },
  {
    title: "Feedback App",
    description: "Feedback app provides a platform for users to rate products",
    image: "/images/feedback.png",
    tags: ["React"],
    source: "https://google.com",
    visit: "https://github.com/mento-mume/feedback-app",
    id: 7,
  },
  {
    title: "Memogen App",
    description:
      "App that helps create memos and downloads a copy unto your local device",
    image: "/images/memogen.png",
    tags: ["React", "docxtemplater", "firebase"],
    source: "https://memogen.vercel.app/",
    visit: "https://github.com/mento-mume/memogen",
    id: 0,
  },
];
